//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import runtime "k8s.io/apimachinery/pkg/runtime"

func (in *ActionSpec) DeepCopyInto(out *ActionSpec) {
	*out = *in
}

func (in *ActionSpec) DeepCopy() *ActionSpec {
	if in == nil {
		return nil
	}
	out := new(ActionSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KiteAgent) DeepCopyInto(out *KiteAgent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *KiteAgent) DeepCopy() *KiteAgent {
	if in == nil {
		return nil
	}
	out := new(KiteAgent)
	in.DeepCopyInto(out)
	return out
}

func (in *KiteAgent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KiteAgentList) DeepCopyInto(out *KiteAgentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KiteAgent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *KiteAgentList) DeepCopy() *KiteAgentList {
	if in == nil {
		return nil
	}
	out := new(KiteAgentList)
	in.DeepCopyInto(out)
	return out
}

func (in *KiteAgentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *KiteAgentSpec) DeepCopyInto(out *KiteAgentSpec) {
	*out = *in
	out.PollInterval = in.PollInterval
	if in.AllowedActions != nil {
		in, out := &in.AllowedActions, &out.AllowedActions
		*out = make([]ActionSpec, len(*in))
		copy(*out, *in)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *KiteAgentSpec) DeepCopy() *KiteAgentSpec {
	if in == nil {
		return nil
	}
	out := new(KiteAgentSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *KiteAgentStatus) DeepCopyInto(out *KiteAgentStatus) {
	*out = *in
}

func (in *KiteAgentStatus) DeepCopy() *KiteAgentStatus {
	if in == nil {
		return nil
	}
	out := new(KiteAgentStatus)
	in.DeepCopyInto(out)
	return out
}
